DROP TABLE IF EXISTS assento_ingresso CASCADE;
DROP TABLE IF EXISTS Cliente_Ingresso CASCADE;
DROP TABLE IF EXISTS elenco CASCADE;
DROP TABLE IF EXISTS Venda CASCADE;

-- GRUPO 3: Tabelas com dependências Nível 2
DROP TABLE IF EXISTS Ingresso CASCADE;
DROP TABLE IF EXISTS Sessao CASCADE;

-- GRUPO 2: Tabelas com dependências Nível 1
DROP TABLE IF EXISTS Filme CASCADE;
DROP TABLE IF EXISTS Assento CASCADE;

-- GRUPO 1: Tabelas Base (Sem dependências externas)
DROP TABLE IF EXISTS Ator CASCADE;
DROP TABLE IF EXISTS Diretor CASCADE;
DROP TABLE IF EXISTS Genero CASCADE;
DROP TABLE IF EXISTS Sala CASCADE;
DROP TABLE IF EXISTS Bomboniere CASCADE;
DROP TABLE IF EXISTS Cliente CASCADE;
DROP TABLE IF EXISTS Funcionario CASCADE;